"""initial schema

Revision ID: 5638fb2a1810
Revises: 
Create Date: 2026-05-07 19:43:06.975115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5638fb2a1810'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('actions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('action_id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('diff', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('max_value', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('logic_type', sa.String(length=64), nullable=True),
    sa.Column('sub_logic_type', sa.String(length=64), nullable=True),
    sa.Column('token_cost', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'action_id', name='uq_actions_user_action')
    )
    op.create_index(op.f('ix_actions_user_id'), 'actions', ['user_id'], unique=False)
    op.create_table('agenda_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.String(length=16), nullable=False),
    sa.Column('day', sa.String(length=8), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.String(length=8), nullable=True),
    sa.Column('end_time', sa.String(length=8), nullable=True),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('label_kind', sa.String(length=16), nullable=False),
    sa.Column('label_id', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_id', name='uq_agenda_user_item')
    )
    op.create_index(op.f('ix_agenda_items_user_id'), 'agenda_items', ['user_id'], unique=False)
    op.create_table('attributes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('attr_id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'attr_id', name='uq_attributes_user_attr')
    )
    op.create_index(op.f('ix_attributes_user_id'), 'attributes', ['user_id'], unique=False)
    op.create_table('logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('log_id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('day_num', sa.Integer(), nullable=False),
    sa.Column('order_in_day', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'log_id', name='uq_logs_user_log')
    )
    op.create_index(op.f('ix_logs_day_num'), 'logs', ['day_num'], unique=False)
    op.create_index(op.f('ix_logs_timestamp'), 'logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_logs_user_id'), 'logs', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'project_id', name='uq_projects_user_project')
    )
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('sequences_state',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('first_activity_date', sa.Date(), nullable=True),
    sa.Column('last_active_date', sa.Date(), nullable=True),
    sa.Column('consecutive_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('skills_acquired',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('skill_id', sa.String(length=32), nullable=False),
    sa.Column('acquired_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'skill_id')
    )
    op.create_table('user_state',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('energy', sa.Integer(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('build_points', sa.Integer(), nullable=False),
    sa.Column('skill_points', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('days_until_next_checkpoint', sa.Integer(), nullable=False),
    sa.Column('last_checkpoint_check', sa.Date(), nullable=True),
    sa.Column('last_token_refill', sa.Date(), nullable=True),
    sa.Column('daily_refill', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_tutorial',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'key')
    )
    op.create_table('attribute_actions',
    sa.Column('attribute_pk', sa.BigInteger(), nullable=False),
    sa.Column('action_id', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['attribute_pk'], ['attributes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attribute_pk', 'action_id')
    )
    op.create_table('project_actions',
    sa.Column('project_pk', sa.BigInteger(), nullable=False),
    sa.Column('action_id', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['project_pk'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_pk', 'action_id')
    )
    op.create_table('project_attributes',
    sa.Column('project_pk', sa.BigInteger(), nullable=False),
    sa.Column('attr_id', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['project_pk'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_pk', 'attr_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_attributes')
    op.drop_table('project_actions')
    op.drop_table('attribute_actions')
    op.drop_table('user_tutorial')
    op.drop_table('user_state')
    op.drop_table('skills_acquired')
    op.drop_table('sequences_state')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_logs_user_id'), table_name='logs')
    op.drop_index(op.f('ix_logs_timestamp'), table_name='logs')
    op.drop_index(op.f('ix_logs_day_num'), table_name='logs')
    op.drop_table('logs')
    op.drop_index(op.f('ix_attributes_user_id'), table_name='attributes')
    op.drop_table('attributes')
    op.drop_index(op.f('ix_agenda_items_user_id'), table_name='agenda_items')
    op.drop_table('agenda_items')
    op.drop_index(op.f('ix_actions_user_id'), table_name='actions')
    op.drop_table('actions')
    op.drop_table('users')
    # ### end Alembic commands ###
