"""add date to user_state

Revision ID: a844b8c6e2c0
Revises: 5638fb2a1810
Create Date: 2026-05-11 11:30:09.864806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a844b8c6e2c0'
down_revision: Union[str, None] = '5638fb2a1810'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_state', sa.Column('date', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_state', 'date')
    # ### end Alembic commands ###
